'use strict';var d=!0,k=null,m=!1;function s(){return function(){}}function x(e){return function(){return this[e]}}
(function(e,q){for(var v=["voodoo"],y=e,D=0;D<v.length-1;++D)y=y[v[D]];y[v[v.length-1]]=new function(){function E(){this.xa={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",
cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",
forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c","indigo ":"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",
lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"}}function z(){this.construct.apply(this,arguments)}function v(a){c.d(0<a.length,"Composite objects must not be empty");var b=a[0],g=this,l;for(l in b)try{"function"===
typeof b[l]&&(g[l]=function(a,b){return function(){for(var c,l=0;l<b.length;++l)c=b[l],c=c[a].apply(c,arguments);return c==b[b.length-1]?g:c}}(l,a))}catch(e){}}function G(){}function y(){}function H(a,b,g){this.A=a;this.F=b;this.fa="undefined"===typeof g?-1:g;this.q=a.model}function A(){}function D(){}function M(){}function p(a,b,g,l){c.i("Creating ThreeJs Camera");this.e=new THREE.Camera;this.J=a;this.W=b;this.C=g;this.B=l;this.ma=this.na=m;this.rb();Object.defineProperty(this,"fovy",{get:x("W"),
set:function(){c.h("fovy is read-only")},n:m});Object.defineProperty(this,"position",{get:function(){return{x:this.e.position.x,y:this.e.position.y,z:this.e.position.z}},set:function(){c.h("position is read-only")},n:m});Object.defineProperty(this,"zNear",{get:x("C"),set:function(){c.h("zNear is read-only")},n:m});Object.defineProperty(this,"zFar",{get:x("B"),set:function(){c.h("zFar is read-only")},n:m})}function I(){c.i("Creating ThreeJs Scene");this.t=new THREE.Scene}function B(a){c.i("Creating ThreeJs Triggers");
this.m=[];this.t=a}function n(a){this.a=a;this.L=[];this.Ra=new THREE.Projector;this.Cb();this.hb();this.ib();this.yb()}function O(){}function w(a){this.a=a;this.qb();this.a.o.qa(0,0);this.bb()}function C(a,b,g,l,e){c.d(b==t.ThreeJs,"Only ThreeJs is supported");this.Qa=a;this.Sa=b;this.va=g;this.Ua=l;this.N=e}function r(){c.i("Creating Options")}function u(a){c.d(a!=k,"Options must not be null");c.d(a.renderer==t.ThreeJs,"Only ThreeJs is supported");c.i("Creating Engine");c.i("   version: 0.8.2");
c.i("   userAgent: "+navigator.userAgent);for(var b in a)c.i("   options."+b+": "+a[b]);!e.WebGLRenderingContext&&c.h("WebGL not supported");this.c=a;!this.c.aboveLayer&&!this.c.belowLayer&&c.h("At least one layer must be enabled");this.s=[];Object.defineProperty(this,"models",{get:function(){for(var a=[],b=0;b<this.s.length;++b)a.push(this.s[b]);return a},set:function(){c.h("models is read-only")},n:m});switch(a.renderer){case t.ThreeJs:this.o=new n(this);break;default:this.o=k,c.h("Unsupported renderer")}this.Da=
new w(this);e.voodoo.engine=this;a.standardLighting&&(c.i("Creating standard lights"),new N({color:"white"}),new L({color:"white"}));a.frameLoop&&(c.i("Beginning frame loop"),this.o.Ta())}E.prototype.convertCssColorToThreeJsColor=function(a){c.d(a,"cssColor undefined");c.d(3<=a.length,"cssColor too short");a=a.toLowerCase();return"#"==a[0]?this.Aa(a):0==a.indexOf("rgb(")?(a=a.substring(4,a.length-1).split(","),c.d(3==a.length,"Invalid rgb color"),this.Ba(a[0],a[1],a[2])):0==a.indexOf("rgba(")?(a=
a.substring(5,a.length-1).split(","),c.d(4==a.length,"Invalid rgba color"),this.Ba(a[0],a[1],a[2])):0==a.indexOf("hsl(")?(a=a.substring(4,a.length-1).split(","),c.d(3==a.length,"Invalid hsl color"),this.za(a[0],a[1],a[2])):0==a.indexOf("hsla(")?(a=a.substring(5,a.length-1).split(","),c.d(4==a.length,"Invalid hsla color"),this.za(a[0],a[1],a[2])):this.gb(a)};E.prototype.findAbsolutePosition=function(a){var b=0,g=0;if(a.offsetParent){do b+=a.offsetLeft,g+=a.offsetTop;while(a=a.offsetParent)}return{x:b,
y:g}};E.prototype.Aa=function(a){return new THREE.Color(parseInt("0x"+a.substring(1),16))};E.prototype.Ba=function(a,b,g){a=parseFloat(a)/255;b=parseFloat(b)/255;g=parseFloat(g)/255;c.d(0<=a,"r value < 0");c.d(1>=a,"r value > 1");c.d(0<=b,"g value < 0");c.d(1>=b,"g value > 1");c.d(0<=g,"b value < 0");c.d(1>=g,"b value > 1");return(new THREE.Color).setRGB(a,b,g)};E.prototype.za=function(a,b,g){a=parseFloat(a);b=parseFloat(b)/100;g=parseFloat(g)/100;c.d(0<=a,"h value < 0");c.d(360>a,"h value >= 360");
c.d(0<=b,"s value < 0");c.d(1>=b,"s value > 1");c.d(0<=g,"l value < 0");c.d(1>=g,"l value > 1");b*=1-Math.abs(2*g-1);var l=a/60,e=b*(1-Math.abs(parseInt(l,10)%2-1)),K=a=0,f=0;0<=l&&1>l?(a=b,K=e):1<=l&&2>l?(a=e,K=b):2<=l&&3>l?(K=b,f=e):3<=l&&4>l?(K=e,f=b):4<=l&&5>l?(a=e,f=b):5<=l&&6>l&&(a=b,f=e);g-=0.5*b;return(new THREE.Color).setRGB(a+g,K+g,f+g)};E.prototype.gb=function(a){c.d("undefined"!==typeof this.xa[a],"Invalid color string");return this.Aa(this.xa[a.toLowerCase()])};this.utility=new E;z.prototype.construct=
function(){throw"Extendable::construct not implemented";};z.extend=function(a){function b(){c.apply(this,arguments)}function g(){}var c=this;b.extend=z.extend;g.prototype=c.prototype;b.prototype=new g;for(var e in a)b.prototype[e]=a[e];return b};this.Extendable=z;G.prototype.ya=function(a){e.console.log("[voodoo] "+a)};G.prototype.i=function(a){this.ya(a)};G.prototype.Na=function(a,b){this.i(a.pb+" "+b)};G.prototype.h=function(a){this.ya("**ERROR** "+a);throw"Voodoo Exception: "+a;};G.prototype.d=
function(a,b){!a&&this.h("Assert failed: "+b)};var c=new G;y.prototype.disableStencils=m;y.prototype.drawStencils=m;this.debug=new y;H.prototype.X=function(a){return a!=k&&this.q==a.q&&this.fa==a.fa};H.prototype.F=k;H.prototype.q=k;H.prototype.fa=-1;H.prototype.A=k;this.j=function(a,b,g){this.type=a;this.model=b;this.triggerId="undefined"===typeof g?-1:g};this.j.prototype.sb=function(a,b,g,c,e,f){this.client.x=a;this.client.y=b;this.hit.x=g;this.hit.y=c;this.hit.z=e;this.button=f||0};this.j.prototype.button=
0;this.j.prototype.client={};this.j.prototype.client.x=Number.MAX_VALUE;this.j.prototype.client.y=Number.MAX_VALUE;this.j.prototype.hit={};this.j.prototype.hit.x=Number.MAX_VALUE;this.j.prototype.hit.y=Number.MAX_VALUE;this.j.prototype.hit.z=Number.MAX_VALUE;this.j.prototype.model=k;this.j.prototype.type=k;this.j.prototype.triggerId=-1;this.Event=this.j;var P=0,f=z.extend();f.prototype.cleanUp=s();f.prototype.construct=function(a){c.d(this.name,"Model type name cannot be undefined or null");c.d(this.viewType,
"Model view type cannot be undefined or null");this.stencilViewType=this.stencilViewType||this.viewType;this.pb="<"+ ++P+","+this.name+">";c.Na(this,"Constructing");if("undefined"===typeof e.voodoo.engine||e.voodoo.engine===k)e.voodoo.engine=new u(new r);"undefined"===typeof e.voodoo.engine||e.voodoo.engine===k?c.h("Engine must be initialized"):(this.G={},this.initialize(a),this.jb(),this.A=1<this.I.length?new v(this.I):this.I[0],this.da=1<this.ea.length?new v(this.ea):this.ea[0],Object.defineProperty(this,
"view",{get:x("A"),set:function(){c.h("view is read-only")},n:m}),Object.defineProperty(this,"stencilView",{get:x("da"),set:function(){c.h("stencilView is read-only")},n:m}),this.setUpViews(),e.voodoo.engine.cb(this))};f.prototype.destroy=function(){c.Na(this,"Destroying");this.tearDownViews();e.voodoo.engine.wb(this);this.A&&this.A.destroy&&this.A.destroy();this.da&&this.da.destroy&&this.da.destroy();this.cleanUp()};f.prototype.extend=function(a){return z.prototype.extend(a)};f.prototype.initialize=
s();f.prototype.on=function(a,b){this.G[a]||(this.G[a]=[]);-1==this.G[a].indexOf(b)&&this.G[a].push(b);return this};f.prototype.off=function(a,b){var g=this.G[a];g&&g.Za(b)&&g.splice(g.Za(b),1);return this};f.prototype.setUpViews=s();f.prototype.stencilView=k;f.prototype.tearDownViews=s();f.prototype.update=s();f.prototype.view=k;f.prototype.Ca=function(a){var b=this.G[a.type];if(b)for(var g=0;g<b.length;++g)b[g].call(this,a)};f.prototype.jb=function(){this.I=[];this.ea=[];for(var a=e.voodoo.engine.o.L,
b=this.stencilViewType==this.viewType,g=0;g<a.length;++g){var c=a[g];switch(c.Qa){case J.Above:(0<this.viewType.prototype.zMax||0==this.viewType.prototype.zMax&&0==this.viewType.prototype.zMin)&&this.I.push(new this.viewType(this,c));break;case J.Below:0>this.viewType.prototype.zMin&&this.I.push(new this.viewType(this,c));break;case J.Stencil:b?this.I.push(new this.viewType(this,c)):this.ea.push(new this.stencilViewType(this,c))}}};f.prototype.name=k;f.prototype.viewType=k;f.prototype.stencilViewType=
k;this.Model=f;var h=z.extend();h.prototype.construct=function(a,b){c.d(a,"View model passed to initialize cannot be null");c.d(b,"View layer passed to initialize cannot be null");this.q=a;this.$=b;this.m=this.$.N.eb(this);Object.defineProperty(this,"camera",{get:function(){return this.$.va},set:function(){c.h("camera is read-only")},n:m});Object.defineProperty(this,"model",{get:x("q"),set:function(){c.h("model is read-only")},n:m});Object.defineProperty(this,"renderer",{get:function(){return this.$.Sa},
set:function(){c.h("renderer is read-only")},n:m});Object.defineProperty(this,"scene",{get:function(){return this.$.Ua},set:function(){c.h("scene is read-only")},n:m});Object.defineProperty(this,"triggers",{get:x("m"),set:function(){c.h("triggers is read-only")},n:m});this.load()};h.prototype.destroy=function(){this.unload()};h.prototype.extend=function(a){return z.prototype.extend(a)};h.prototype.load=s();h.prototype.unload=s();h.prototype.camera=k;h.prototype.model=k;h.prototype.renderer=k;h.prototype.scene=
k;h.prototype.triggers=k;h.prototype.zMax=Number.POSITIVE_INFINITY;h.prototype.zMin=Number.NEGATIVE_INFINITY;this.View=h;A.prototype.fovY=k;A.prototype.position={};A.prototype.position.x={};A.prototype.position.y={};A.prototype.position.z={};A.prototype.zNear=k;A.prototype.zFar=k;D.prototype.add=s();D.prototype.remove=s();M.prototype.add=s();M.prototype.remove=s();p.prototype=new A;p.prototype.fovY=k;p.prototype.position={};p.prototype.position.x={};p.prototype.position.y={};p.prototype.position.z=
{};p.prototype.zNear=k;p.prototype.zFar=k;p.prototype.rb=function(){this.e.up.x=0;this.e.up.y=-1;this.e.up.z=0;this.Oa();this.O();var a=this;e.addEventListener("scroll",function(){a.Pa()},m);e.addEventListener("resize",function(){a.Oa()},m);this.v=d};p.prototype.Pa=function(){this.na=d};p.prototype.Oa=function(){this.ma=d;this.Pa()};p.prototype.Va=function(a,b){this.C=a;this.B=b;this.e.projectionMatrix.makePerspective(this.W,this.sa,this.C,this.B);this.v=d};p.prototype.O=function(){if(this.ma){this.sa=
this.J.width/this.J.height;var a=Math.tan(this.W/360*Math.PI);this.Db=this.J.height/2/a;this.e.projectionMatrix.makePerspective(this.W,this.sa,this.C,this.B);this.e.position.z=this.Db;this.e.scale.x=-1;this.ma=m;this.v=d}this.na&&(this.e.position.x=this.J.width/2+e.pageXOffset,this.e.position.y=this.J.height/2+e.pageYOffset,this.e.lookAt(new THREE.Vector3(this.e.position.x,this.e.position.y,0)),this.na=m,this.v=d)};p.prototype.v=m;p.prototype.e=k;I.prototype=new M;I.prototype.add=function(a){a.addedToVoodooTriggers?
a.visible=d:this.t.add(a);a.addedToVoodooScene=d};I.prototype.remove=function(a){this.t.remove(a);a.addedToVoodooTriggers?a.visible=m:this.t.add(a);a.addedToVoodooScene=m};B.prototype=new D;B.prototype.add=function(a,b,g){c.d(a,"View must be valid");c.d(b,"Object must be valid");a=new H(a,b,g);for(g=0;g<this.m.length;++g)this.m[g].F==a.F&&c.h("Trigger already exists");this.m.push(a);b.addedToVoodooScene||(b.visible=m,this.t.add(b));b.addedToVoodooTriggers=d};B.prototype.remove=function(a){for(var b=
0;b<this.m.length;++b)this.m[b].F==a&&this.m.splice(b,1);a.addedToVoodooScene&&this.t.remove(a);a.addedToVoodooTriggers=m};B.prototype.eb=function(a){var b=this;return{add:function(c,l){b.add(a,c,l)},remove:function(a){b.remove(a)}}};B.prototype.m=k;n.prototype.kb=function(){this.a.c.aboveLayer&&q.body.removeChild(this.Q);this.a.c.belowLayer&&q.body.removeChild(this.ha)};n.prototype.frame=function(){this.O();this.xb()};n.prototype.Ta=function(){var a=this;requestAnimationFrame(function(){a.Ta()});
this.frame()};n.prototype.wa=function(a){this.a.c.aboveLayer&&(this.Q.style.pointerEvents=a?"auto":"none")};n.prototype.hb=function(){c.i("Creating WebGL renderers");var a={antialias:this.a.c.antialias};this.a.c.aboveLayer&&(this.S=new THREE.WebGLRenderer(a),this.Q=this.S.domElement,this.Wa(this.S),this.Q.style.zIndex=this.a.c.aboveZIndex);this.a.c.belowLayer&&(this.f=new THREE.WebGLRenderer(a),this.ha=this.f.domElement,this.Wa(this.f),this.ha.style.zIndex=this.a.c.belowZIndex)};n.prototype.ib=function(){c.i("Creating layers");
var a=this.a.c.renderer;this.a.c.aboveLayer&&(this.p=new p(this.Q,this.a.c.fovY,this.a.c.C,this.a.c.B),this.ga=new I,this.ab=new B(this.ga),this.ra=new C(J.Above,a,this.p,this.ga,this.ab),this.L.push(this.ra));this.a.c.belowLayer&&(this.k=new p(this.ha,this.a.c.fovY,this.a.c.C,this.a.c.B),this.ia=new I,this.ca=new I,this.fb=new B(this.ia),this.zb=new B(this.ca),this.ta=new C(J.Below,a,this.k,this.ia,this.fb),this.Xa=new C(J.Stencil,a,this.k,this.ca,this.zb),this.L.push(this.ta),this.L.push(this.Xa));
this.oa=m;this.Ya();var b=this;e.addEventListener("resize",function(){b.oa=d},m)};n.prototype.Ea=function(a,b){for(var c=this.ra.N.m,l=0;l<c.length;++l){var e=c[l],f=e.q,h=this.$a.intersectObject(e.F,d);if(!(0>=h.length)&&!(0>=h[0].distance||h[0].distance>=a.V))if(!this.a.c.belowLayer||!(0>h[0].point.z&&0>e.A.zMin&&f.viewType!=f.stencilViewType&&-1===b.indexOf(f)))a.V=h[0].distance,a.M=e,a.pa=h[0].point}return a};n.prototype.Fa=function(a,b){for(var c=this.ta.N.m,l=0;l<c.length;++l){var e=c[l],f=
e.q,h=e.F;if(!this.a.c.aboveLayer||!(0<f.view.zMax||0<=f.view.zMin))if(h=this.ua.intersectObject(h,d),!(0>=h.length)&&!(0<=h[0].point.z)&&!(0>=h[0].distance||h[0].distance>=a.V)&&!(f.viewType!=f.stencilViewType&&-1===b.indexOf(f)))a.V=h[0].distance,a.M=e,a.pa=h[0].point}return a};n.prototype.Ga=function(){for(var a=[],b=this.Xa.N.m,c=0;c<b.length;++c){var l=b[c],e=l.F,f=l.q;f.viewType!==f.stencilViewType&&(0<=l.A.zMin||-1===b.indexOf(f)&&0<this.ua.intersectObject(e,d).length&&a.push(f))}return a};
n.prototype.lb=function(){var a=q.createElement("div");a.style.cssText="position: fixed; top: 0; left: 0; bottom: 0; right: 0;";q.documentElement.insertBefore(a,q.documentElement.firstChild);var b={width:a.offsetWidth,height:a.offsetHeight};q.documentElement.removeChild(a);return b};n.prototype.ba=function(){var a={V:Number.MAX_VALUE,M:k,pa:k};if(this.a.c.belowLayer&&this.a.c.aboveLayer)var b=this.Ga(),a=this.Ea(a,b),a=this.Fa(a,b);else this.a.c.aboveLayer?a=this.Ea(a,[]):this.a.c.belowLayer&&(b=
this.Ga(),a=this.Fa(a,b));b=a.pa;return{M:a.M,mb:b?b.x:Number.MAX_VALUE,nb:b?b.y:Number.MAX_VALUE,ob:b?b.z:Number.MAX_VALUE}};n.prototype.xb=function(){if(e.voodoo.debug.drawStencils)this.a.c.belowLayer&&(this.f.context.disable(this.f.context.STENCIL_TEST),this.f.autoClear=d,this.f.render(this.ca.t,this.k.e));else{if(this.a.c.belowLayer){if(e.voodoo.debug.disableStencils)this.f.context.disable(this.f.context.STENCIL_TEST),this.f.autoClear=d;else{this.f.context.enable(this.f.context.STENCIL_TEST);
this.f.context.clearStencil(0);this.f.context.stencilOp(this.f.context.REPLACE,this.f.context.REPLACE,this.f.context.REPLACE);this.f.context.stencilFunc(this.f.context.NEVER,1,4294967295);this.f.autoClear=m;this.f.clear();this.f.render(this.ca.t,this.k.e);var a=this.f.context;a.stencilOp(a.KEEP,a.KEEP,a.KEEP);a.stencilFunc(a.EQUAL,1,4294967295)}this.f.render(this.ia.t,this.k.e)}this.a.c.aboveLayer&&this.S.render(this.ga.t,this.p.e)}this.a.c.aboveLayer&&this.S.context.finish();this.a.c.belowLayer&&
this.f.context.finish()};n.prototype.yb=function(){c.i("Starting timers");var a=this;this.Z=this.D=0;e.addEventListener("focus",function(){a.D=0;setTimeout(function(){a.D=Date.now()},a.a.c.Ab)},m);e.addEventListener("blur",function(){a.D=0},m);setTimeout(function(){a.D=Date.now()},a.a.c.Bb)};n.prototype.Wa=function(a){function b(){h.left=e.pageXOffset+"px";h.top=e.pageYOffset+"px"}function c(){l.P=l.lb();var b=l.P.width,g=l.P.height;a.setSize(b,g);h.width=b;h.height=g;f.width=b;f.height=g;q.body.style.display=
"none";q.body.style.display="block"}var l=this,f=a.domElement,h=f.style;a.setFaceCulling(THREE.CullFaceFront,THREE.FrontFaceDirectionCCW);h.position="absolute";c();b();h.pointerEvents="none";q.body.appendChild(f);e.addEventListener("scroll",b,m);e.addEventListener("resize",c,m)};n.prototype.qa=function(a,b){var c=0,e=0;"undefined"!==typeof this.P&&(c=2*(a/this.P.width)-1,e=2*-(b/this.P.height)+1);this.a.c.aboveLayer&&(this.R=new THREE.Vector3(c,e,1),this.Ra.unprojectVector(this.R,this.p.e),this.R=
this.R.sub(this.p.e.position).normalize(),this.$a=new THREE.Raycaster(this.p.e.position,this.R));this.a.c.belowLayer&&(this.T=new THREE.Vector3(c,e,1),this.Ra.unprojectVector(this.T,this.k.e),this.T=this.T.sub(this.k.e.position).normalize(),this.ua=new THREE.Raycaster(this.k.e.position,this.T))};n.prototype.O=function(){var a=0,b=Date.now();0!=this.D&&(a=(b-this.D)/1E3,this.D=b);a>2*this.Z?(b=this.Z,this.Z=a,a=b):this.Z=a;this.a.c.aboveLayer&&this.p.O();this.a.c.belowLayer&&this.k.O();this.oa&&(this.Ya(),
this.oa=m);if(this.a.c.aboveLayer&&this.p.v||this.a.c.belowLayer&&this.k.v){for(var b=this.a.s,c=new e.voodoo.Event("cameramove"),f=0;f<b.length;++f)b[f].Ca(c);this.a.c.aboveLayer&&(this.p.v=m);this.a.c.belowLayer&&(this.k.v=m)}b=this.a.s;for(f=0;f<b.length;++f)b[f].update(a);this.a.Da.update()};n.prototype.Ya=function(){if(this.a.c.belowLayer){var a=this.k.position.z;this.k.Va(a-0.5,this.a.c.B)}this.a.c.aboveLayer&&(a=this.p.position.z,this.p.Va(this.a.c.C,a))};n.prototype.Cb=function(){c.i("Validating and preparing webpage for use");
c.d(q.body,"document.body is undefined");q.body.style.width="100%";q.body.style.height="100%";q.body.style.margin="0px"};n.prototype.L=k;var t={ThreeJs:0};O.prototype.ba=s();O.prototype.qa=s();this.Renderer=t;w.prototype.update=function(){this.aa&&this.a.o.qa(this.ja,this.ka);var a=this.ba();a!=k?(this.aa&&this.u("mousemove",a),a.X(this.l)||(this.l!=k&&this.u("mouseout",this.l),this.u("mouseover",a)),this.a.o.wa(d)):(this.l!=k&&this.u("mouseout",this.l),this.a.o.wa(m));this.l=a;this.aa=m};w.prototype.bb=
function(){var a=this;q.addEventListener("mousemove",function(b){a.ub(b)},m);q.addEventListener("mousedown",function(b){a.tb(b)},m);q.addEventListener("mouseup",function(b){a.vb(b)},m)};w.prototype.u=function(a,b,c){a=new e.voodoo.Event(a,b.q,b.fa);a.sb(this.ja,this.ka,this.Ka,this.La,this.Ma,c);b.q.Ca(a)};w.prototype.qb=function(){this.l=k;this.K=[k,k,k];this.Y=[k,k,k];this.Eb=m;this.la=[m,m,m];this.aa=m;this.Ma=this.La=this.Ka=this.ka=this.ja=0;this.Ja=[k,k,k];this.Ha=[0,0,0];this.Ia=[0,0,0]};w.prototype.tb=
function(a){if(this.l!=k){a.preventDefault();var b=this.Y[a.button],c=new Date-this.Ja[a.button];this.K[a.button]=this.l;this.u("mousedown",this.l,a.button);this.K[a.button].X(b)&&(this.Ha[a.button]==a.clientX&&this.Ia[a.button]==a.clientY&&500>=c)&&(this.la[a.button]=d)}};w.prototype.ub=function(a){this.l!=k&&a.preventDefault();this.ja=a.clientX;this.ka=a.clientY;this.aa=d};w.prototype.vb=function(a){if(this.l!=k){a.preventDefault();this.u("mouseup",this.l,a.button);var b=this.K[a.button],c=this.Y[a.button];
this.l.X(b)&&(this.u("click",this.K[a.button],a.button),this.la[a.button]&&b.X(c)?(this.Y[a.button]=k,this.la[a.button]=m,this.u("dblclick",b,a.button)):(this.Y[a.button]=b,this.Ja[a.button]=new Date,this.Ha[a.button]=a.clientX,this.Ia[a.button]=a.clientY))}this.K[a.button]=k};w.prototype.ba=function(){var a=this.a.o.ba();this.Ka=a.mb;this.La=a.nb;this.Ma=a.ob;return a.M};var J={Above:0,Below:1,Stencil:2};C.prototype.Qa=k;C.prototype.Sa=k;C.prototype.va=k;C.prototype.Ua=k;C.prototype.N=k;r.prototype.aboveLayer=
d;r.prototype.aboveZIndex=1E4;r.prototype.antialias=d;r.prototype.belowLayer=d;r.prototype.belowZIndex=-1;r.prototype.fovY=30;r.prototype.frameLoop=d;r.prototype.renderer=t.ThreeJs;r.prototype.standardLighting=d;r.prototype.Ab=350;r.prototype.Bb=1E3;r.prototype.B=1E4;r.prototype.C=0.1;this.Options=r;u.prototype.destroy=function(){c.i("Destroying Engine");for(var a=0;a<this.s.length;++a)this.s[a].destroy();this.s=k;this.o.kb();"undefined"!==typeof e.voodoo.engine&&delete e.voodoo.engine};u.prototype.frame=
function(){this.o.frame()};u.prototype.models=k;u.prototype.cb=function(a){this.s.push(a)};u.prototype.wb=function(a){this.s.splice(this.s.indexOf(a),1)};u.prototype.Da=k;u.prototype.c=k;this.engine=u.prototype.o=k;this.Engine=u;this.version=k;var F=h.extend();F.prototype.createLight=function(){throw"createLight_() undefined.";};F.prototype.load=function(){c.d(this.renderer==t.ThreeJs,"Only ThreeJs is supported");this.H=this.createLight();this.scene.add(this.H)};F.prototype.unload=function(){c.d(this.renderer==
t.ThreeJs,"Only ThreeJs is supported");this.scene.remove(this.H)};F.prototype.setColor=function(a){c.d(this.renderer==t.ThreeJs,"Only ThreeJs is supported");a=e.voodoo.utility.convertCssColorToThreeJsColor(a);this.H.color.copy(a)};f=f.extend();f.prototype.initialize=function(a){this.U=a&&a.color?a.color:k;Object.defineProperty(this,"color",{get:x("U"),set:function(a){this.view.setColor(a);this.U=a},n:d})};f.prototype.setUpViews=function(){this.color=this.U?this.U:"black"};f.prototype.color=k;f.prototype.stencilViewType=
h.extend();h=F.extend();h.prototype.createLight=function(){c.d(this.renderer==t.ThreeJs,"Only ThreeJs is supported");return new THREE.AmbientLight};var N=f.extend();N.prototype.name="AmbientLight";N.prototype.viewType=h;h=F.extend();h.prototype.createLight=function(){c.d(this.renderer==t.ThreeJs,"Only ThreeJs is supported");return new THREE.PointLight};h.prototype.load=function(){F.prototype.load.apply(this);this.updatePosition()};h.prototype.updatePosition=function(){c.d(this.renderer==t.ThreeJs,
"Only ThreeJs is supported");this.H.position.x=this.camera.position.x;this.H.position.y=this.camera.position.y;this.H.position.z=this.camera.position.z};var L=f.extend();L.prototype.name="CameraLight";L.prototype.viewType=h;L.prototype.setUpViews=function(){this.on("cameramove",function(){this.view.updatePosition()})}};y[v[v.length-1]].version="0.8.2"})(window,document,void 0);
